### ISSUE TITLE
Arghhh… DR fjerner flere podcasts

### ISSUE THREAD

**Issue by SlyngelDk** [drpodcastnu/drpodcastnu.github.io#5]
Flere podcasts forsvinder nu fra DR’s offentlige RSS. Senest er P6 beat programmet DEBUT forsvundet.
Er det muligt at foreslå tilføjelser til projektet? Og hvordan gør jeg i så fald? (Tilgiv min uvidenhed - men har oprettet en GitHub konto blot for at kunne skrive her, så fatter ikke megen GitHub lingo)

**Comment by drpodcastnu** [comment]
Jeg arbejder på at få lavet en automatisk opdatering af de podcasts som bliver fjernet

**Comment by drpodcastnu** [comment]
Så er det fixet :) @SlyngelDk
